In [55]:
import numpy as np

ARRAY OPERATIONS

1. Arithmetic operations

In [56]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [57]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [58]:
a1-a2

array([-5, -5, -5, -5, -5])

In [59]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [60]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [61]:
a1%a2

array([1, 2, 3, 4, 5])

In [62]:
a1//a2

array([0, 0, 0, 0, 0])

In [63]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

2. Broadcasting

In [64]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [65]:
arr+10


array([20, 30, 40, 50])

In [66]:
arr*2

array([20, 40, 60, 80])

In [67]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [68]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [69]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

3. Deep and Shallow copy

In [70]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [72]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
a[4:6]*10

array([50, 60])

4. Matrix operations

In [78]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [79]:
B

array([[5, 6],
       [7, 8]])

In [82]:
A+B

array([[ 6,  8],
       [10, 12]])

In [81]:
A @ B

array([[19, 22],
       [43, 50]])

In [83]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

Transpose

In [84]:
A.T

array([[1, 3],
       [2, 4]])

In [85]:
B.T

array([[5, 7],
       [6, 8]])

5. Advance Array Manipulation


Stacking Array

In [86]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [87]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [89]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [91]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [93]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
a=np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [95]:
for i in a:
    print(a)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
