In [29]:
import numpy as np

Valid Sudoku

In [30]:
s = np.array([
[5, 3, 4, 6, 7, 8, 9, 1, 2],
[6, 7, 2, 1, 9, 5, 3, 4, 8],
[1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [31]:
b = np.sum(s, axis=1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
    else:
        print("for row it is valid")
        break

for row it is valid


In [32]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("sudoku is not valid")
        break
    else:
        print("for row it is valid")
        break

for row it is valid


In [33]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [35]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [36]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General question

In [38]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
[18, 85,78],    # Student 1
[19, 92, 88],   # Student 2
[17, 76,95],    # Student 3
[18, 65,70],    # Student 4
[20,90,85]      # Student 5
])



In [39]:
#Get the shape of the matrix
data.shape


(5, 3)

In [41]:
#find the avg age of students
np.mean(data[:,0])


np.float64(18.4)

In [42]:
#Extract math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [43]:
#Get details of the student who scored more than 90 in Math.

data [data [: ,1] > 90]

array([[19, 92, 88]])