In [9]:
import numpy as np

Basic Array Creation

In [10]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [13]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Random Generation Function

In [23]:
np.random.rand(3)

array([0.92124764, 0.00128169, 0.32495474])

In [24]:
np.random.randn(10)

array([-0.2669124 , -1.46070505,  0.78690246,  0.95068529, -0.53459839,
        0.03781229, -0.0200979 ,  0.8101002 , -0.11012399,  1.01069507])

In [27]:
np.random.randint(10,20,10)

array([19, 19, 16, 16, 18, 18, 10, 19, 16, 19], dtype=int32)

Array Attributes

In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.shape

(3, 3)

In [32]:
arr.size

9

In [33]:
arr.dtype

dtype('int64')

Array Methods

In [35]:
arr.min()

np.int64(1)

In [36]:
arr.max()

np.int64(9)

In [37]:
arr.sum()

np.int64(45)

In [38]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [39]:
np.sum(arr , axis=1)

array([ 6, 15, 24])

In [40]:
arr.mean()

np.float64(5.0)

In [41]:
arr.std()

np.float64(2.581988897471611)

In [42]:
arr.argmax()

np.int64(8)

In [43]:
arr.argmin()

np.int64(0)

In [45]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])