In [2]:
import numpy as np

## NUMPY INDEXING AND SLICING OF VECTORS


In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[4]

np.int64(15)

In [5]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [6]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## NUMPY INDEXING AND SLICING OF MATRIX

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[0]

array([1, 2, 3, 4, 5])

In [9]:
arr[3]

array([16, 17, 18, 19, 20])

In [10]:
arr[0,0]

np.int64(1)

In [11]:
arr[4,4]

np.int64(25)

In [12]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [13]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [14]:
arr[: , 2]

array([ 3,  8, 13, 18, 23, 28])

## BOOLEAN INDEXING

In [15]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [21]:
arr=np.array([[[1,2,3,4,5]]])
print(arr)

[[[1 2 3 4 5]]]


In [26]:
list1 = [10, 20, 30, 40, 50]

arr1 = np.array(list1)

print("1D Array:")
print(arr1)


1D Array:
[10 20 30 40 50]


In [29]:
list2 = [
    [1, 2, 3],
    [4, 5, 6]
]

arr2 = np.array(list2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [31]:
list3 = [[1,2,3], [4,5,6],[7,8,9]
   
]

arr3 = np.array(list3)

print("\n3D Array:")
print(arr3)


3D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(np.__version__)

2.4.6


In [38]:
print(arr1[2]*arr1[3])

1200


In [37]:
print(arr3[1]+arr3[2])
print(arr2[0])

[11 13 15]
[1 2 3]
