In [1]:
import numpy as np

## ARRAY OPERATIONS

1. Arithmetic operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1%a2

array([1, 2, 3, 4, 5])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

2. Broadcasting

In [10]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [11]:
arr+10


array([20, 30, 40, 50])

In [12]:
arr*2

array([20, 40, 60, 80])

In [13]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [15]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

3. Deep and Shallow copy

In [16]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
a[4:6]*10

array([50, 60])

4. Matrix operations

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [21]:
B

array([[5, 6],
       [7, 8]])

In [22]:
A+B

array([[ 6,  8],
       [10, 12]])

In [23]:
A @ B

array([[19, 22],
       [43, 50]])

In [24]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

Transpose

In [25]:
A.T

array([[1, 3],
       [2, 4]])

In [26]:
B.T

array([[5, 7],
       [6, 8]])

5. Advance Array Manipulation


Stacking Array

In [27]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [28]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [32]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [34]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [35]:
a=np.vsplit(c,4)

In [36]:
for i in a:
    print(a)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


## hello


In [37]:
list = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [38]:
list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
newArray = arr.reshape(2,2)


# Concatenate

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
a = np.array([0,1],[2,3])
b = np.resize(a,(2,4))

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [ ]:
a = np.array([0,1],[2,3])
b = np.reshape(a,(2,4))

TypeError: Field elements must be 2- or 3-tuples, got '2'