In [1]:
import numpy as np

Basic Array Creation

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [5]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [8]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Random Generation Function

In [9]:
np.random.rand(3)

array([0.0417695 , 0.92430603, 0.44266436])

In [10]:
np.random.randn(10)

array([ 0.04315464, -0.91077553, -1.47483792,  1.90532778, -1.5144697 ,
        0.26084319,  0.05401802, -0.35241387,  1.2296408 ,  0.45866134])

In [11]:
np.random.randint(10,20,10)

array([15, 17, 18, 13, 11, 16, 15, 18, 13, 18], dtype=int32)

Array Attributes

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.shape

(3, 3)

In [14]:
arr.size

9

In [15]:
arr.dtype

dtype('int64')

Array Methods

In [16]:
arr.min()

np.int64(1)

In [17]:
arr.max()

np.int64(9)

In [18]:
arr.sum()

np.int64(45)

In [19]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [20]:
np.sum(arr , axis=1)

array([ 6, 15, 24])

In [21]:
arr.mean()

np.float64(5.0)

In [22]:
arr.std()

np.float64(2.581988897471611)

In [23]:
arr.argmax()

np.int64(8)

In [24]:
arr.argmin()

np.int64(0)

In [25]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [29]:
list = np.array([4,5,3,7,1])
print(list)

[4 5 3 7 1]


In [30]:
np.sort(list)

array([1, 3, 4, 5, 7])

In [31]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
np.arange(0,24,10)


array([ 0, 10, 20])

In [34]:
np.linspace(0,24,10)

array([ 0.        ,  2.66666667,  5.33333333,  8.        , 10.66666667,
       13.33333333, 16.        , 18.66666667, 21.33333333, 24.        ])